# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\tapi.proto"A\n\x04News\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\x0c"\x1b\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t2&\n\x03\x41pi\x12\x1f\n\tsend_news\x12\x05.News\x1a\t.Response"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "api_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NEWS"]._serialized_start = 13
    _globals["_NEWS"]._serialized_end = 78
    _globals["_RESPONSE"]._serialized_start = 80
    _globals["_RESPONSE"]._serialized_end = 107
    _globals["_API"]._serialized_start = 109
    _globals["_API"]._serialized_end = 147
# @@protoc_insertion_point(module_scope)
